### ISSUE TITLE
Alembic confused by new database

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/BookServer#106]
If you try to run an alembic migration on a database that has been created by a docker build you end up in a bad state.

1. The created database is created fresh from the models, and has no need of a migration.
2. But if you do some development and now want to do a migration or create a migration for use elsewhere alembic thinks it needs to start over from the first revision. -- which naturally errors out because it does not need to do the earlier migrations.
3. Alembic uses the table alembic_version to keep track.  Its simple.

```
create table alembic_version ( version_num varchar(32) not null );
```

alembic puts the latest revision in the table so it knows where it **should** start.

Somewhere in our build / initialization process for docker we should insert the command

```
alembic stamp head
```

This will create the table and populate it with the latest.

@bjones1 -- pinging you FYI -- or maybe you know right where to put this in the build process?

It may be obvious but I guess I should add that this should not be done for production.  It would maybe be nice to automatically run the migration on a production build, but I think I feel more comfortable running migrations manually.

**Comment by bjones1** [comment]
I'm testing a fix. How does that look?

The approach: stamp the database only when it's first populated by running `rsmanage initdb`. (In the future, this seems like it should actually go inside the `rsmanage initdb` code.) So, while this *would* happen in production, it would only be when first initializing and empty database, but never after that.
